name: Compile Examples
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - board:
              fqbn: Inkplate_Boards:esp32:Inkplate6
            additional-sketch-paths: |
              - examples
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install ESP32 platform dependencies
        run: pip3 install pyserial
      - name: Compile examples
        uses: arduino/compile-sketches@v1.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          platforms: |
            - source-url: https://github.com/SolderedElectronics/Dasduino-Board-Definitions-for-Arduino-IDE/raw/master/package_Dasduino_Boards_index.json
              name: Inkplate_Boards:esp32

          fqbn: ${{ matrix.board.fqbn }}
          libraries: |
            - source-path: https://github.com/SolderedElectronics/Soldered-MFRC522-RFID-Reader-Arduino-Library.git
          sketch-paths: |
            ${{ matrix.additional-sketch-paths }}
          cli-compile-flags: |
            - --warnings="default"
