name: Compile Examples
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - board:
              fqbn: esp32:esp32:esp32
            additional-sketch-paths: |
              - examples
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install ESP32 platform dependencies
        run: pip3 install pyserial
      - name: Compile examples
        uses: arduino/compile-sketches@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          platforms: |
            - source-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
              name: esp32:esp32

          fqbn: ${{ matrix.board.fqbn }}
          libraries: |
            - source-path: ./
            - name: "Adafruit BME680 Library"
            - name: ArduinoJson
            - name: Time
          sketch-paths: |
            ${{ matrix.additional-sketch-paths }}
          cli-compile-flags: |
            - "--warnings none"
